frontend:
  - changed-files:
    - any-glob-to-any-file:
      - src/**/*
      - public/**/*
      - package.json
      - tailwind.config.js

backend:
  - changed-files:
    - any-glob-to-any-file: Backend/**/*

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

workflows:
  - changed-files:
    - any-glob-to-any-file: .github/workflows/**/*
